[package]
name = "tezos-codec"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runtime = { git = "https://gitlab.com/archaephyrryx/codec_generator" }
gen = { git = "https://gitlab.com/archaephyrryx/codec_generator", features = ["full"] }
sha2 = "0.10.6"
base58 = "0.2.0"